### ISSUE TITLE
Controller for resolver 

### ISSUE THREAD

**Issue by zelima** [datahq/resolver#2]
Create controller that gets requests with path `username/pkgname` eg: `https://api.datahub.io/resolver?path=core/financefix` and responds with same userid and package 
`{userid: <userid>, pkgname: <pkcgname>}`

## Acceptance criteria

* [x] when I hit `/resolver/resolve?path=owner/name` I get json response with `userid` and `packageid`

## Tasks

* [x] refactor controller to hit `auth` service with given username and return object based on that
* [x] update tests

**Comment by zelima** [comment]
FIXED

**Comment by rufuspollock** [comment]
@zelima i don't understand how this is FIXED. The whole point of the resolver is to give the userid when given a username or userid. This does nothing useful atm.

What is in the way of looking up the userid?

**Comment by zelima** [comment]
@rufuspollock I agree, it does nothing useful for now, but we can not do anything more until we have API from auth, as said in issue description:
>Note: for now respond with same user and package id (Until we wire into Auth)

**Comment by rufuspollock** [comment]
@zelima and what's the blocked to have this in auth and where is the issue for that? Definitely link the blocking issue in auth from this issue 😄

**Comment by anuveyatsu** [comment]
@rufuspollock I have added the issue from `auth` as a blocker for this issue. Once `auth` is done I will fix that issue (and will update estimate, description and tasks).

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/resolver/commit/87e8ea2c8b8ebf5ff0f6c63b06f0a992950fe45e
